<center>
<img src="https://laelgelcpublic.s3.sa-east-1.amazonaws.com/lael_50_years_narrow_white.png.no_years.400px_96dpi.png" width="300" alt="LAEL 50 years logo">
<h3>APPLIED LINGUISTICS GRADUATE PROGRAMME (LAEL)</h3>
</center>
<hr>

# Corpus Linguistics - Study 1 - Phase 1 - Andrea

This document aims to organise the data collection for this project.

## Import `TV_commercials_1950_2025.xlsx` into a pandas DataFrame

In [1]:
import pandas as pd

tv_commercials_df = pd.read_excel(
    "corpus/00_sources/TV_commercials_1950_2025.xlsx",
    engine="openpyxl"
)

In [3]:
tv_commercials_df = tv_commercials_df.drop(columns=["Unnamed: 7", "Unnamed: 8"])

## Add sequential video identifiers

In [5]:
unique_video_ids = {
    url: f"video_{index:04d}"
    for index, url in enumerate(tv_commercials_df["URL"].drop_duplicates(), start=1)
}

video_id_position = tv_commercials_df.columns.get_loc("Category") + 1

tv_commercials_df.insert(
    video_id_position,
    "Video ID",
    tv_commercials_df["URL"].map(unique_video_ids)
)

## List repeated videos

In [7]:
repeated_videos_df = (
    tv_commercials_df["Video ID"]
    .value_counts()
    .loc[lambda counts: counts > 1]
    .reset_index()
)

repeated_videos_df.columns = ["Video ID", "Occurrences"]

repeated_videos_df

      Video ID  Occurrences
0   video_0180           72
1   video_0460           64
2   video_0118           44
3   video_0233           12
4   video_0231            8
5   video_0229            6
6   video_0142            5
7   video_0172            5
8   video_0072            4
9   video_0109            4
10  video_0143            3
11  video_0293            3
12  video_0146            2
13  video_0149            2
14  video_0382            2

## Add commercial identifiers

In [8]:
commercial_id_position = tv_commercials_df.columns.get_loc("Category") + 1

tv_commercials_df.insert(
    commercial_id_position,
    "Commercial ID",
    (
            "tv_com_"
            + tv_commercials_df["Decade"].astype(str)
            + "_"
            + tv_commercials_df["Sequence"].astype(str)
    )
)

tv_commercials_df

,Decade,Sequence,Title,Category,Commercial ID,Video ID,URL,Start,End
0,1950,1,Norwich Liquid Peptans,"Health, Beauty & Personal Care",tv_com_1950_1,video_0001,https://youtu.be/G-zZFNf4PqQ,0:00:00,0:00:59
1,1950,2,Betty Crocker Cake,"Food, Beverages & Nutrition",tv_com_1950_2,video_0002,https://youtu.be/WMIMxj0PGGY,0:00:17,0:01:43
2,1950,3,Easy Clean Kentile Vinyl Asbestos Floor,"Household, Cleaning & Home Care",tv_com_1950_3,video_0003,https://youtu.be/O-baiygWMTQ,0:00:00,0:01:01
3,1950,4,Johnson's Floor Wax Polisher Scrubber,"Household, Cleaning & Home Care",tv_com_1950_4,video_0004,https://youtu.be/GGcZsStUjTg,0:00:00,0:01:31
4,1950,5,Best Foods Hellmann's Real Mayonnaise,"Food, Beverages & Nutrition",tv_com_1950_5,video_0005,https://youtu.be/bh6rDLrRcsc,0:00:00,0:01:01
...,...,...,...,...,...,...,...,...,...
955,2020,116,2025 Dell Technologies Holiday Help,"Technology, Communication & Eletronics",tv_com_2020_116,video_0735,https://youtu.be/ijGcSPZ4T8s,0:00:00,0:00:15
956,2020,117,2026 Chevrolet See the USA featuring Brooke Lee,"Personal, Public Transport & Travel",tv_com_2020_117,video_0736,https://youtu.be/g-6nRs4BqXQ,0:00:00,0:01:01
957,2020,118,2022 Southern Company Equitable Future,"Personal, Public Transport & Travel",tv_com_2020_118,video_0737,https://youtu.be/WybuYYSr3sw,0:00:00,0:01:01
958,2020,119,2023 Exxon Mobil Reduce Carbon Emissions,"Personal, Public Transport & Travel",tv_com_2020_119,video_0738,https://youtu.be/sYNhUg7mmnU,0:00:00,0:00:31
959,2020,120,2026 Delta Air Lines Olympics: What We Carry,"Personal, Public Transport & Travel",tv_com_2020_120,video_0739,https://youtu.be/WX1wgKCVJzc,0:00:00,0:00:30

## Save metadata as NDJSON

In [9]:
tv_commercials_df.to_json(
    "corpus/00_sources/tv_commercials.ndjson",
    orient="records",
    lines=True,
    force_ascii=False
)